# +———————————————————————————————————————————————————+ #
# |——————————     BANITEM CONFIGURATION     ——————————| #
# |——————————————————      v2.1      —————————————————| #
# +———————————————————————————————————————————————————+ #
# |                   Documentation:                  | #
# |             http://banitem.andross.fr/            | #
# +———————————————————————————————————————————————————+ #
# For any bugs/suggestions: Andross#5254
# +——————————————————————————————————————————————————————————————————————————————————————————————+
# General Informations:
#  - The blacklist will block the items.
#  - The whitelist will allow only the items set.
#    -> The 'message' key represents the message sent to players if they try to use an item which is not in whitelist
#    -> The 'ignored' key represents all ignored options (they will not being by default banned)
#
#  - Worlds can be written:
#    -> single: 'world' ; 'world_the_end'...
#    -> multiple: 'world, world_the_end'...
#    -> all: '*'
#    -> all except: '*, !world_the_end, !world_nether': all worlds, except world_the_end & world_nether
#
#  - Items can be written: (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html)
#    -> single: 'stone' ; 'dirt'...
#    -> multiple: 'stone, dirt'
#    -> all: '*' (also include air [=empty hand]!)
#    -> all except: '*, !stone' (all, except stone)
#
#  - Options can be written:
#    -> single: 'place' ; 'break'...
#    -> multiple: 'place, break'
#    -> all: '*'
#    -> all except: '*, !place' (all, except place))
#  - Each options can store some datas to check. They can be written, for example (except for cooldown & log):
#    -> entity: pig, cow
#    -> entity:
#       - pig
#       - cow
#    -> entity:
#       - pig,cow
#
#   - Options data: (if none set, this will apply for all) - (* can be useable for all options involving a player)
#     -> cooldown(*): allow access to the option each X milliseconds (1 second = 1000 milliseconds)
#     -> entity: the entity interacted or involved in the ban
#       -> EntityType: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
#     -> gamemode(*): the item is only banned if the player is in this gamemode
#     -> inventory-from: the inventory where the item come from
#       -> InventoryType: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/InventoryType.html
#     -> inventory-to: the inventory where the item goes to (same type as above)
#     -> material: an additional item checked
#       -> For example, in a BREAK option, this data will also check a matches with the item in the player's hand
#       -> https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#     -> log(*): true/false - if players with /banitem log will receive a message for this ban
#     -> message(*): a string or list of string to be sent if the item is banned
#     -> metadata(*): the metadata that the item should have:
#       -> 'displayname-equals': string - if the item displayname is equals to this (e.g: displayname-equals: 'test')
#       -> 'displayname-contains': string - if the item displayname contains this (e.g: displayname-contains: 'test')
#       -> 'lore-equals': list - if the item lore is equals to this
#       -> 'lore-contains': string/list - if the item lore contains this
#       -> 'durability': short - if the item durability is equals to this (e.g: durability: 3)
#       -> 'enchantment-equals': string/list - if the item enchantments is equals to this (e.g: enchantment-equals: 'SILK_TOUCH:1')
#       -> 'enchantment-contains': string/list - if the item enchantments contains all this (e.g: enchantment-contains: 'SILK_TOUCH:1')
#       -> 'potion': string/list - if the item contains this potion (e.g: potion: 'SPEED')
#        +——————————————————————————————————————————————————————+
#  - Options and their possibles datas:
#    - ARMORSTANDPLACE: when the player try to place the item on an armorstand [no specific data]
#    - ARMORSTANDTAKE: when the player try to take the item from an armorstand [no specific data]
#    - ATTACK: when the player use left click with the item in the main hand on an entity
#      -> Special data: entity - the entity clicked
#    - BREAK: when the item is breaked
#      -> Special data: material - the item in the player hand
#    - BREW: when the item (potion) is brewed inside a brewing stand [no specific data]
#    - CLICK: when the player use left click with the item in the main hand
#      -> Special data: material - the block clicked, if there is one
#    - CONSUME: when the player try to consume a food [no specific data]
#    - CRAFT: the item will not be craftable anymore [no specific data]
#    - DELETE: when a player open & close an inventory, it will check and delete items which have this option [no specific data]
#    - DISPENSE: when an item is dispensed from a block [no specific data]
#    - DROP: when an item is dropped by a player [no specific data]
#    - DROPS: when an item is dropped from a block
#      -> Special data: material - the item in the player's hand
#    - ENTITYDROP: when an entity dies and drop the item
#      -> Special data: entity - the entity type
#    - ENTITYINTERACT: when a player use right click with the item on an entity
#      -> Special data: entity - the entity interacted
#    - GLIDE: when a player try to use (activate) an elytra [no specific data]
#    - HANGINGPLACE: when a player try to place a hanging entity (itemframe, painting..)
#      -> Special data: entity - the entity created by this placing
#    - INTERACT: when the player use right click with main hand on the placed item
#      -> Special data: material - the item in player's hand
#    - PICKUP: when the item is picked up [no specific data]
#    - PLACE: when the player use right click, so the item is placed or used
#      -> Special data: material - the block clicked, if there is one
#    - SMELT: the item will not be smeltable anymore [no specific data]
#    - SWAP: when the player try to swap the item in hands [no specific data]
#    - TRANSFER: when the player try to transfer the item from an inventory to another
#      -> Special data:
#        -> inventory-from: the inventory where the item comes from
#        -> inventory-to: the inventory where the item goes to
#    - WEAR: when the player try to put the item as an armor (you'll need to use also the 'place' option) [no specific data]
#        +——————————————————————————————————————————————————————+
#  - Examples:
#    -> Simple structure:
#      blacklist:  ##----> for blacklist
#        world: ##----> world where the ban should apply
#          ender_pearl: ##----> the item
#            place: '&cYou can not use ender pearls in world.' ##----> the option with a message
#                        +————————————————————+
#    -> Advanced structure:
#      blacklist:  ##----> for blacklist
#       'world, world_the_end': ##----> worlds where the ban should apply
#         'dirt, stone': ##----> the items
#           'place, break': ##----> the options, and below their datas
#             message: ##----> a configurable (multi-line, or not) message
#             - '&cA first message example'
#             - '&cA second message example'
#             gamemode: creative ##----> only applies if player is in creative
#             log: true: ##----> players with /bi log activated will receive a message
#             cooldown: 30000 ##----> this ban only applies each 30 seconds (players can only either break or place the items each 30 seconds)
# +——————————————————————————————————————————————————————————————————————————————————————————————+

# Better & more detailled loading error messages
better-debug: true

# Block hoppers to take/give banned item from/to inventories (items must have the 'transfer' option)
hoppers-block: false

# No permission message (for /banitem)
no-permission: '&cYou do not have permission.'

# This will allow the plugin to call 'PlayerBanItemEvent' whenever an item is banned
# This is used to allow others plugins to modify the behavior
use-event-api: false

# List of options that should have maximum listening priority
# Giving maximum priority will force the ban item plugin to have the final word on an event
# This is used mainly to also block other plugins events, if the action is banned
# You can use the options formatting ('*', 'option1, option2', '*,!break' etc.)
priority: place,consume

# Animations when a ban item message is sent
sound:
  enabled: true
  type: ENCHANT_THORNS_HIT
  volume: 1
  pitch: 1
  worldSound: false # if the sound can be heard by others players around or not
#particle: # available only on bukkit 1.9+
#  enabled: true
#  type: BARRIER
#  amount: 1

# Here is some quick examples:
#blacklist:
#  world:
#    diamond_block: # can not place or break diamond_block
#      place: '&cYou are not allowed to place a diamond block in world.'
#      break: '&cYou are not allowed to break a diamond block in world.'
#    gold_block: # can not place gold block if in creative mode
#      place:
#        gamemode: creative
#        message: '&cYou can not place gold block while in creative mode.'
#    my_custom_item: # custom item from /bi customitem, useable only each minute (time in millis)
#      attack:
#        cooldown: 60000
#        message: '&cYou have to wait &e{time}&c before attacking with this item again.'
#    stick: # can not put stick into an itemframe. Sending log message to players with /bi log activated.
#      entityinteract:
#        entity: item_frame
#        message: '&cYou can not put a stick into an itemframe!'
#        log: true
#    diamond_sword: # can not attack with a diamond sword with display name 'test'
#      attack: # can not attack with diamond sword, with this displayname
#        message: '&cNo sword with text ''test''!'
#        metadata:
#          displayname-equals: 'test'
#    diamond: # can not put diamonds from a player inventory to a chest
#      transfer:
#        inventory-from: player
#        inventory-to: chest
#        message: '&cYou can not put diamonds in chests.'
#  '*, !world_the_end':
#    ender_pearl:
#      place: '&cYou can use enderpearls only in the end.'

#whitelist:
#  world_the_end:
#    message: '&cOnly thing allowed in this world: placing dirt.'
#    ignored: 'interact' # we ignore the interact, so player can interact (to place) with everything
#    dirt: place # dirt can be placed
### Whitelist conclusion: in world_the_end, only one thing is allowed: placing dirt.
### Everything else (breaking, pickup, drop etc.) will be blocked.
