# +———————————————————————————————————————————————————+ #
# |——————————     BANITEM CONFIGURATION     ——————————| #
# |——————————————————      v1.9      —————————————————| #
# +———————————————————————————————————————————————————+ #
# For any bugs/suggestions: Andross#5254
#
# -- Informations: --
#   - Blacklist contains list of blocked items
#   - Whitelist contains list of allowed items only, so the following options are blocked:
#      - Placing, breaking, picking up, dropping, interacting & dispensing items which are not on whitelist
#   - Worlds can be written single 'world', multiple 'world, world_the_end', or you can include all worlds with '*'
#   - Options can be written single 'break', multiple 'break, place' or you can include all options with '*'. Using '*!' will not include creative.
#
# Blacklist: block ...
# - place: when the item is placed or used
# - break: when the item is breaked
# - pickup: when the item is picked up
# - drop: when the item is dropped
# - interact: when the player use right click with main hand on the placed item
# - creative: applies only if the player is in creative mode
# - inventory: when the player try to take/put the item from/in an inventory
# - dispense: when an item is dispensed from a block
#
# Whitelist: allow ...
# - place: place or use the item
# - break: break the item
# - pickup: pick up the item
# - drop: drop the item
# - interact: when the player use right click with main hand on the item (Have to be almost always used, as you first interact with the clicked block)
# - inventory: when the player try to take/put the item from/in an inventory
# - dispense: an item to be dispensed from a block
# The 'message' key represents the message sent to players if they try to use an item which is not in whitelist
# The 'ignored' key represents all ignored options (they will not being by default banned)

# No permission message (for /banitem)
no-permission: '&cYou do not have permission.'

# Message cooldown when player try to pickup a banned item (in milliseconds)
pickup-message-cooldown: 1000

blacklist:
  world:
    diamond_block:
      place: '&cYou are not allowed to place a diamond block in world.'
      break: '&cYou are not allowed to break a diamond block in world.'
    stone_button:
      interact: '&cYou can not interact with a stone button in world.'
      pickup: '&cYou can not pickup a stone button in world.'
    lava_bucket:
      place, creative: '&cYou can not use lava buckets in this world while in creative mode.'
    my_custom_potion:
      place: '&cYou can not use potion of speed I in world.'
  world_the_end:
    ender_pearl:
      place: '&cYou can not use enderpearls in the end.'
whitelist:
  world_the_end:
    message: '&cYou can only place and break ender stone in the end.'
    ignored: inventory, pickup, drop
    ender_stone: place, interact, break