name: BanItem
main: fr.andross.banitem.BanItem
version: '1.9.9.3'
author: _Andross
description: Ban item
api-version: '1.13'
commands:
  banitem:
    description: Banitem command. Show help.
    permission: banitem.command
    aliases: [bi]
permissions:
  banitem.bypass.*:
    description: bypass the ban item in all worlds
  banitem.command.*:
    description: use /banitem command.
    children:
      banitem.command.check: true
      banitem.command.customitem: true
      banitem.command.help: true
      banitem.command.info: true
      banitem.command.reload: true
