name: BanItem
main: fr.andross.banitem.Plugin
version: '1.5'
author: _Andross
description: Ban item
api-version: '1.13'
commands:
  banitem:
    description: Banitem command. Show help.
permissions:
  banitem.bypass.*:
    default: op
    description: bypass the ban item in all worlds
  banitem.command:
    default: op
    description: use /banitem command.
    children:
      banitem.command.reload: true
      banitem.command.info: true
