name: BanItem
main: fr.banitem.BanItem
version: 1.3
author: _Andross
description: Ban item
commands:
  banitem:
    description: Banitem command. Show help.
permissions:
  banitem.bypass.*:
    default: op
    description: bypass the banitem in all worlds
  banitem.command:
    default: op
    description: use /banitem command.
    children:
      banitem.command.reload: true
