name: BanItem
main: fr.andross.Plugin
version: '1.4'
author: _Andross
description: Ban item
commands:
  banitem:
    description: Banitem command. Show help.
permissions:
  banitem.bypass.*:
    default: op
    description: bypass the ban item in all worlds
  banitem.command:
    default: op
    description: use /banitem command.
    children:
      banitem.command.reload: true
