name: BanItem
main: fr.andross.banitem.BanItem
version: '3.4'
author: Andross
description: Ban item
api-version: '1.13'
softdepend: [AdvancedEnchantments, ItemsAdder, NBTAPI, WorldGuard]
commands:
  banitem:
    description: Banitem command. Show help.
    permission: banitem.command.help
    aliases: [bi]
permissions:
  banitem.bypass.*:
    description: bypass the ban item in all worlds
  banitem.command:
    description: use /banitem command.
    children:
      banitem.command.add: true
      banitem.command.check: true
      banitem.command.help: true
      banitem.command.info: true
      banitem.command.load: true
      banitem.command.log: true
      banitem.command.metaitem: true
      banitem.command.reload: true
      banitem.command.remove: true
  banitem.bypassillegalstack:
    description: permission to bypass the illegalstack scanner
